db = db.getSiblingDB('trubbi_test')
db.events_test.drop()
db.events_test.insertMany(
{
    image: 'img', 
    title: 'Choripaneada', 
    calle: 'paseo de la costa',
    altura: 900, 
    barrio: 'Olivos',
    date: '21-05-2022', 
    time_start: '19:30',    
    time_end: '00:00', 
    description: 'Es una evento en donde diferente parrilleros especializados en chori van a estar realizando choripanes y algjunos sanguchitos de diferentes cortes vacunos',
    cathegory: 'Gastonomia',
    techado: false,
    capacidad: 2000,
    activo: true,
    autorizado: true,
    proveedor: 'siga la vaca'
},
{
    image: 'img', 
    title: 'Cocina Vegana', 
    calle: 'avenida san martin',
    altura: 5020, 
    barrio: 'Florida',
    date: '01-05-2022', 
    time_start: '12:00',    
    time_end: '18:00', 
    description: 'Es una evento en donde diferente parrilleros especializados en chori van a estar realizando choripanes y algjunos sanguchitos de diferentes cortes vacunos',
    cathegory: 'Gastonomia',
    techado: false,
    capacidad: 2000,
    activo: true,
    autorizado: true,
    proveedor: 'grupo vegano'
},
{
    image: 'img', 
    title: 'Choripaneada', 
    calle: 'avenida santa fe',
    altura: 5020, 
    barrio: 'Palermo',
    date: '21-05-2022', 
    time_start: '19:30',    
    time_end: '00:00', 
    description: 'Es una evento en donde diferente parrilleros especializados en chori van a estar realizando choripanes y algjunos sanguchitos de diferentes cortes vacunos',
    cathegory: 'Gastonomia',
    techado: false,
    capacidad: 2000,
    activo: true,
    autorizado: true,
    proveedor: 'siga la vaca'
},
{
    image: 'img', 
    title: 'Choripaneada', 
    calle: 'avenida santa fe',
    altura: 5020, 
    barrio: 'Palermo',
    date: '21-05-2022', 
    time_start: '19:30',    
    time_end: '00:00', 
    description: 'Es una evento en donde diferente parrilleros especializados en chori van a estar realizando choripanes y algjunos sanguchitos de diferentes cortes vacunos',
    cathegory: 'Gastonomia',
    techado: false,
    capacidad: 2000,
    activo: true,
    autorizado: true,
    proveedor: 'siga la vaca'
},
{
    image: 'img', 
    title: 'Choripaneada', 
    calle: 'avenida santa fe',
    altura: 5020, 
    barrio: 'Palermo',
    date: '21-05-2022', 
    time_start: '19:30',    
    time_end: '00:00', 
    description: 'Es una evento en donde diferente parrilleros especializados en chori van a estar realizando choripanes y algjunos sanguchitos de diferentes cortes vacunos',
    cathegory: 'Gastonomia',
    techado: false,
    capacidad: 2000,
    activo: true,
    autorizado: true,
    proveedor: 'siga la vaca'
},
{
    image: 'img', 
    title: 'Choripaneada', 
    calle: 'avenida santa fe',
    altura: 5020, 
    barrio: 'Palermo',
    date: '21-05-2022', 
    time_start: '19:30',    
    time_end: '00:00', 
    description: 'Es una evento en donde diferente parrilleros especializados en chori van a estar realizando choripanes y algjunos sanguchitos de diferentes cortes vacunos',
    cathegory: 'Gastonomia',
    techado: false,
    capacidad: 2000,
    activo: true,
    autorizado: true,
    proveedor: 'siga la vaca'
},
{
    image: 'img', 
    title: 'Choripaneada', 
    calle: 'avenida santa fe',
    altura: 5020, 
    barrio: 'Palermo',
    date: '21-05-2022', 
    time_start: '19:30',    
    time_end: '00:00', 
    description: 'Es una evento en donde diferente parrilleros especializados en chori van a estar realizando choripanes y algjunos sanguchitos de diferentes cortes vacunos',
    cathegory: 'Gastonomia',
    techado: false,
    capacidad: 2000,
    activo: true,
    autorizado: true,
    proveedor: 'siga la vaca'
},
{
    image: 'img', 
    title: 'Choripaneada', 
    calle: 'avenida santa fe',
    altura: 5020, 
    barrio: 'Palermo',
    date: '21-05-2022', 
    time_start: '19:30',    
    time_end: '00:00', 
    description: 'Es una evento en donde diferente parrilleros especializados en chori van a estar realizando choripanes y algjunos sanguchitos de diferentes cortes vacunos',
    cathegory: 'Gastonomia',
    techado: false,
    capacidad: 2000,
    activo: true,
    autorizado: true,
    proveedor: 'siga la vaca'
},
{
    image: 'img', 
    title: 'Choripaneada', 
    calle: 'avenida santa fe',
    altura: 5020, 
    barrio: 'Palermo',
    date: '21-05-2022', 
    time_start: '19:30',    
    time_end: '00:00', 
    description: 'Es una evento en donde diferente parrilleros especializados en chori van a estar realizando choripanes y algjunos sanguchitos de diferentes cortes vacunos',
    cathegory: 'Gastonomia',
    techado: false,
    capacidad: 2000,
    activo: true,
    autorizado: true,
    proveedor: 'siga la vaca'
},
{
    image: 'img', 
    title: 'Choripaneada', 
    calle: 'avenida santa fe',
    altura: 5020, 
    barrio: 'Palermo',
    date: '21-05-2022', 
    time_start: '19:30',    
    time_end: '00:00', 
    description: 'Es una evento en donde diferente parrilleros especializados en chori van a estar realizando choripanes y algjunos sanguchitos de diferentes cortes vacunos',
    cathegory: 'Gastonomia',
    techado: false,
    capacidad: 2000,
    activo: true,
    autorizado: true,
    proveedor: 'siga la vaca'
},
{
    image: 'img', 
    title: 'Choripaneada', 
    calle: 'avenida santa fe',
    altura: 5020, 
    barrio: 'Palermo',
    date: '21-05-2022', 
    time_start: '19:30',    
    time_end: '00:00', 
    description: 'Es una evento en donde diferente parrilleros especializados en chori van a estar realizando choripanes y algjunos sanguchitos de diferentes cortes vacunos',
    cathegory: 'Gastonomia',
    techado: false,
    capacidad: 2000,
    activo: true,
    autorizado: true,
    proveedor: 'siga la vaca'
},
{
    image: 'img', 
    title: 'Choripaneada', 
    calle: 'avenida santa fe',
    altura: 5020, 
    barrio: 'Palermo',
    date: '21-05-2022', 
    time_start: '19:30',    
    time_end: '00:00', 
    description: 'Es una evento en donde diferente parrilleros especializados en chori van a estar realizando choripanes y algjunos sanguchitos de diferentes cortes vacunos',
    cathegory: 'Gastonomia',
    techado: false,
    capacidad: 2000,
    activo: true,
    autorizado: true,
    proveedor: 'siga la vaca'
},
{
    image: 'img', 
    title: 'Choripaneada', 
    calle: 'avenida santa fe',
    altura: 5020, 
    barrio: 'Palermo',
    date: '21-05-2022', 
    time_start: '19:30',    
    time_end: '00:00', 
    description: 'Es una evento en donde diferente parrilleros especializados en chori van a estar realizando choripanes y algjunos sanguchitos de diferentes cortes vacunos',
    cathegory: 'Gastonomia',
    techado: false,
    capacidad: 2000,
    activo: true,
    autorizado: true,
    proveedor: 'siga la vaca'
},
{
    image: 'img', 
    title: 'Choripaneada', 
    calle: 'avenida santa fe',
    altura: 5020, 
    barrio: 'Palermo',
    date: '21-05-2022', 
    time_start: '19:30',    
    time_end: '00:00', 
    description: 'Es una evento en donde diferente parrilleros especializados en chori van a estar realizando choripanes y algjunos sanguchitos de diferentes cortes vacunos',
    cathegory: 'Gastonomia',
    techado: false,
    capacidad: 2000,
    activo: true,
    autorizado: true,
    proveedor: 'siga la vaca'
},
{
    image: 'img', 
    title: 'Choripaneada', 
    calle: 'avenida santa fe',
    altura: 5020, 
    barrio: 'Palermo',
    date: '21-05-2022', 
    time_start: '19:30',    
    time_end: '00:00', 
    description: 'Es una evento en donde diferente parrilleros especializados en chori van a estar realizando choripanes y algjunos sanguchitos de diferentes cortes vacunos',
    cathegory: 'Gastonomia',
    techado: false,
    capacidad: 2000,
    activo: true,
    autorizado: true,
    proveedor: 'siga la vaca'
},
{
    image: 'img', 
    title: 'Choripaneada', 
    calle: 'avenida santa fe',
    altura: 5020, 
    barrio: 'Palermo',
    date: '21-05-2022', 
    time_start: '19:30',    
    time_end: '00:00', 
    description: 'Es una evento en donde diferente parrilleros especializados en chori van a estar realizando choripanes y algjunos sanguchitos de diferentes cortes vacunos',
    cathegory: 'Gastonomia',
    techado: false,
    capacidad: 2000,
    activo: true,
    autorizado: true,
    proveedor: 'siga la vaca'
},
{
    image: 'img', 
    title: 'Choripaneada', 
    calle: 'avenida santa fe',
    altura: 5020, 
    barrio: 'Palermo',
    date: '21-05-2022', 
    time_start: '19:30',    
    time_end: '00:00', 
    description: 'Es una evento en donde diferente parrilleros especializados en chori van a estar realizando choripanes y algjunos sanguchitos de diferentes cortes vacunos',
    cathegory: 'Gastonomia',
    techado: false,
    capacidad: 2000,
    activo: true,
    autorizado: true,
    proveedor: 'siga la vaca'
},
{
    image: 'img', 
    title: 'Choripaneada', 
    calle: 'avenida santa fe',
    altura: 5020, 
    barrio: 'Palermo',
    date: '21-05-2022', 
    time_start: '19:30',    
    time_end: '00:00', 
    description: 'Es una evento en donde diferente parrilleros especializados en chori van a estar realizando choripanes y algjunos sanguchitos de diferentes cortes vacunos',
    cathegory: 'Gastonomia',
    techado: false,
    capacidad: 2000,
    activo: true,
    autorizado: true,
    proveedor: 'siga la vaca'
},
{
    image: 'img', 
    title: 'Choripaneada', 
    calle: 'avenida santa fe',
    altura: 5020, 
    barrio: 'Palermo',
    date: '21-05-2022', 
    time_start: '19:30',    
    time_end: '00:00', 
    description: 'Es una evento en donde diferente parrilleros especializados en chori van a estar realizando choripanes y algjunos sanguchitos de diferentes cortes vacunos',
    cathegory: 'Gastonomia',
    techado: false,
    capacidad: 2000,
    activo: true,
    autorizado: true,
    proveedor: 'siga la vaca'
},
{
    image: 'img', 
    title: 'Choripaneada', 
    calle: 'avenida santa fe',
    altura: 5020, 
    barrio: 'Palermo',
    date: '21-05-2022', 
    time_start: '19:30',    
    time_end: '00:00', 
    description: 'Es una evento en donde diferente parrilleros especializados en chori van a estar realizando choripanes y algjunos sanguchitos de diferentes cortes vacunos',
    cathegory: 'Gastonomia',
    techado: false,
    capacidad: 2000,
    activo: true,
    autorizado: true,
    proveedor: 'siga la vaca'
},
{
    image: 'img', 
    title: 'Choripaneada', 
    calle: 'avenida santa fe',
    altura: 5020, 
    barrio: 'Palermo',
    date: '21-05-2022', 
    time_start: '19:30',    
    time_end: '00:00', 
    description: 'Es una evento en donde diferente parrilleros especializados en chori van a estar realizando choripanes y algjunos sanguchitos de diferentes cortes vacunos',
    cathegory: 'Gastonomia',
    techado: false,
    capacidad: 2000,
    activo: true,
    autorizado: true,
    proveedor: 'siga la vaca'
}


)